baseURL = 'https://williamlwclwc.github.io/william-hugo/'
defaultContentLanguage = 'en'
locale = 'en-us'
title = 'William Liu'
theme = 'dream'
enableRobotsTXT = true

[params]
lightTheme = "emerald"
darkTheme = "forest"

author = "William Liu"
description = "William Liu's Blog"
avatar = "img/avatar.png"
headerTitle = "William Liu"
motto = "Part of the journey is the end."

siteStartYear = 2026

rss = true

favicon = "img/avatar.png"

stickyNav = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
reorderNavItems = ["homepage", "search", "rss", "posts", "categories", "tags"]

[params.navItems]
homepage = { href = "https://williamlwclwc.github.io", target = "_blank", title = "About" }
