baseURL = 'https://williamlwclwc.github.io/william-hugo/'
defaultContentLanguage = 'en'
locale = 'en-us'
title = 'William Liu'
theme = 'dream'
enableRobotsTXT = true

[params]
lightTheme = "emerald"
darkTheme = "forest"

author = "William Liu"
description = "William Liu's personal blog"
avatar = "img/avatar.png"
headerTitle = "William Liu"
motto = "Your motto here."

siteStartYear = 2026

rss = true

favicon = "favicon.ico"

stickyNav = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
