baseURL = 'https://williamlwclwc.github.io/william-hugo/'
defaultContentLanguage = 'en'
title = 'William Liu'
theme = 'dream'
enableRobotsTXT = true

[languages]
  [languages.en]
    contentDir = 'content/en'
    label = 'English'
    locale = 'en-us'
    weight = 1
    [languages.en.params]
      shortLabel = 'EN'
    [languages.en.params.navItems]
      homepage = { href = "https://williamlwclwc.github.io", target = "_blank", title = "About" }
  [languages.zh]
    contentDir = 'content/zh'
    label = '中文'
    locale = 'zh-Hans'
    weight = 2
    [languages.zh.params]
      shortLabel = '中'
    [languages.zh.params.navItems]
      homepage = { href = "https://williamlwclwc.github.io", target = "_blank", title = "关于" }

[params]
lightTheme = "emerald"
darkTheme = "forest"

author = "William Liu"
description = "William Liu's Blog"
avatar = "img/avatar.png"
headerTitle = "William Liu"
motto = "Part of the journey is the end."

siteStartYear = 2026

rss = true

favicon = "img/avatar.png"

stickyNav = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
reorderNavItems = ["homepage", "search", "rss", "posts", "categories", "tags"]

